openapi: 3.0.1
info:
  title: '@jupiterone/graph-addigy'
  description: A JupiterOne Integration for ingesting data from Addigy
  x-cortex-git:
    github:
      repository: JupiterOne/graph-addigy
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-addigy'
  x-cortex-service-groups:
    - tier-4
